// Generated by gencpp from file pr2_msgs/PeriodicCmd.msg
// DO NOT EDIT!


#ifndef PR2_MSGS_MESSAGE_PERIODICCMD_H
#define PR2_MSGS_MESSAGE_PERIODICCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pr2_msgs
{
template <class ContainerAllocator>
struct PeriodicCmd_
{
  typedef PeriodicCmd_<ContainerAllocator> Type;

  PeriodicCmd_()
    : header()
    , profile()
    , period(0.0)
    , amplitude(0.0)
    , offset(0.0)  {
    }
  PeriodicCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , profile(_alloc)
    , period(0.0)
    , amplitude(0.0)
    , offset(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _profile_type;
  _profile_type profile;

   typedef double _period_type;
  _period_type period;

   typedef double _amplitude_type;
  _amplitude_type amplitude;

   typedef double _offset_type;
  _offset_type offset;




  typedef boost::shared_ptr< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> const> ConstPtr;

}; // struct PeriodicCmd_

typedef ::pr2_msgs::PeriodicCmd_<std::allocator<void> > PeriodicCmd;

typedef boost::shared_ptr< ::pr2_msgs::PeriodicCmd > PeriodicCmdPtr;
typedef boost::shared_ptr< ::pr2_msgs::PeriodicCmd const> PeriodicCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_msgs::PeriodicCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr2_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'pr2_msgs': ['/home/joe/repos/GummiArm/orchestration/packages/src/pr2_common/pr2_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95ab7e548e3d4274f83393129dd96c2e";
  }

  static const char* value(const ::pr2_msgs::PeriodicCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95ab7e548e3d4274ULL;
  static const uint64_t static_value2 = 0xf83393129dd96c2eULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_msgs/PeriodicCmd";
  }

  static const char* value(const ::pr2_msgs::PeriodicCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message is used to set the parameters of a profile executed by the\n\
# laser tilt controller.\n\
Header header\n\
string profile\n\
float64 period\n\
float64 amplitude\n\
float64 offset\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pr2_msgs::PeriodicCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.profile);
      stream.next(m.period);
      stream.next(m.amplitude);
      stream.next(m.offset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PeriodicCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_msgs::PeriodicCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_msgs::PeriodicCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "profile: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.profile);
    s << indent << "period: ";
    Printer<double>::stream(s, indent + "  ", v.period);
    s << indent << "amplitude: ";
    Printer<double>::stream(s, indent + "  ", v.amplitude);
    s << indent << "offset: ";
    Printer<double>::stream(s, indent + "  ", v.offset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_MSGS_MESSAGE_PERIODICCMD_H
