// Generated by gencpp from file pr2_msgs/PressureState.msg
// DO NOT EDIT!


#ifndef PR2_MSGS_MESSAGE_PRESSURESTATE_H
#define PR2_MSGS_MESSAGE_PRESSURESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pr2_msgs
{
template <class ContainerAllocator>
struct PressureState_
{
  typedef PressureState_<ContainerAllocator> Type;

  PressureState_()
    : header()
    , l_finger_tip()
    , r_finger_tip()  {
    }
  PressureState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , l_finger_tip(_alloc)
    , r_finger_tip(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _l_finger_tip_type;
  _l_finger_tip_type l_finger_tip;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _r_finger_tip_type;
  _r_finger_tip_type r_finger_tip;




  typedef boost::shared_ptr< ::pr2_msgs::PressureState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_msgs::PressureState_<ContainerAllocator> const> ConstPtr;

}; // struct PressureState_

typedef ::pr2_msgs::PressureState_<std::allocator<void> > PressureState;

typedef boost::shared_ptr< ::pr2_msgs::PressureState > PressureStatePtr;
typedef boost::shared_ptr< ::pr2_msgs::PressureState const> PressureStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_msgs::PressureState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_msgs::PressureState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr2_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'pr2_msgs': ['/home/joe/repos/GummiArm/orchestration/packages/src/pr2_common/pr2_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr2_msgs::PressureState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_msgs::PressureState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_msgs::PressureState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_msgs::PressureState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_msgs::PressureState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_msgs::PressureState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_msgs::PressureState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "756fb3b75fa8884524fd0789a78eb04b";
  }

  static const char* value(const ::pr2_msgs::PressureState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x756fb3b75fa88845ULL;
  static const uint64_t static_value2 = 0x24fd0789a78eb04bULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_msgs::PressureState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_msgs/PressureState";
  }

  static const char* value(const ::pr2_msgs::PressureState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_msgs::PressureState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Output from finger-tip pressure sensors on PR2\n\
#Higher number correspond to more pressure, but there is no explicit unit and you will have to calibrate for offset\n\
#The numbers reported are the raw values from the I2C hardware\n\
\n\
Header header\n\
int16[] l_finger_tip\n\
int16[] r_finger_tip\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pr2_msgs::PressureState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_msgs::PressureState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.l_finger_tip);
      stream.next(m.r_finger_tip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PressureState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_msgs::PressureState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_msgs::PressureState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "l_finger_tip[]" << std::endl;
    for (size_t i = 0; i < v.l_finger_tip.size(); ++i)
    {
      s << indent << "  l_finger_tip[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.l_finger_tip[i]);
    }
    s << indent << "r_finger_tip[]" << std::endl;
    for (size_t i = 0; i < v.r_finger_tip.size(); ++i)
    {
      s << indent << "  r_finger_tip[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.r_finger_tip[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_MSGS_MESSAGE_PRESSURESTATE_H
