// Generated by gencpp from file pr2_msgs/SetPeriodicCmd.msg
// DO NOT EDIT!


#ifndef PR2_MSGS_MESSAGE_SETPERIODICCMD_H
#define PR2_MSGS_MESSAGE_SETPERIODICCMD_H

#include <ros/service_traits.h>


#include <pr2_msgs/SetPeriodicCmdRequest.h>
#include <pr2_msgs/SetPeriodicCmdResponse.h>


namespace pr2_msgs
{

struct SetPeriodicCmd
{

typedef SetPeriodicCmdRequest Request;
typedef SetPeriodicCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPeriodicCmd
} // namespace pr2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pr2_msgs::SetPeriodicCmd > {
  static const char* value()
  {
    return "daeb6e862b732192bc82a7ea52bb7975";
  }

  static const char* value(const ::pr2_msgs::SetPeriodicCmd&) { return value(); }
};

template<>
struct DataType< ::pr2_msgs::SetPeriodicCmd > {
  static const char* value()
  {
    return "pr2_msgs/SetPeriodicCmd";
  }

  static const char* value(const ::pr2_msgs::SetPeriodicCmd&) { return value(); }
};


// service_traits::MD5Sum< ::pr2_msgs::SetPeriodicCmdRequest> should match 
// service_traits::MD5Sum< ::pr2_msgs::SetPeriodicCmd > 
template<>
struct MD5Sum< ::pr2_msgs::SetPeriodicCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pr2_msgs::SetPeriodicCmd >::value();
  }
  static const char* value(const ::pr2_msgs::SetPeriodicCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pr2_msgs::SetPeriodicCmdRequest> should match 
// service_traits::DataType< ::pr2_msgs::SetPeriodicCmd > 
template<>
struct DataType< ::pr2_msgs::SetPeriodicCmdRequest>
{
  static const char* value()
  {
    return DataType< ::pr2_msgs::SetPeriodicCmd >::value();
  }
  static const char* value(const ::pr2_msgs::SetPeriodicCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pr2_msgs::SetPeriodicCmdResponse> should match 
// service_traits::MD5Sum< ::pr2_msgs::SetPeriodicCmd > 
template<>
struct MD5Sum< ::pr2_msgs::SetPeriodicCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pr2_msgs::SetPeriodicCmd >::value();
  }
  static const char* value(const ::pr2_msgs::SetPeriodicCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pr2_msgs::SetPeriodicCmdResponse> should match 
// service_traits::DataType< ::pr2_msgs::SetPeriodicCmd > 
template<>
struct DataType< ::pr2_msgs::SetPeriodicCmdResponse>
{
  static const char* value()
  {
    return DataType< ::pr2_msgs::SetPeriodicCmd >::value();
  }
  static const char* value(const ::pr2_msgs::SetPeriodicCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PR2_MSGS_MESSAGE_SETPERIODICCMD_H
