// Generated by gencpp from file dynamixel_controllers/SetComplianceMargin.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CONTROLLERS_MESSAGE_SETCOMPLIANCEMARGIN_H
#define DYNAMIXEL_CONTROLLERS_MESSAGE_SETCOMPLIANCEMARGIN_H

#include <ros/service_traits.h>


#include <dynamixel_controllers/SetComplianceMarginRequest.h>
#include <dynamixel_controllers/SetComplianceMarginResponse.h>


namespace dynamixel_controllers
{

struct SetComplianceMargin
{

typedef SetComplianceMarginRequest Request;
typedef SetComplianceMarginResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetComplianceMargin
} // namespace dynamixel_controllers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_controllers::SetComplianceMargin > {
  static const char* value()
  {
    return "daacbf1c0642fe923f2dfb9217a97b81";
  }

  static const char* value(const ::dynamixel_controllers::SetComplianceMargin&) { return value(); }
};

template<>
struct DataType< ::dynamixel_controllers::SetComplianceMargin > {
  static const char* value()
  {
    return "dynamixel_controllers/SetComplianceMargin";
  }

  static const char* value(const ::dynamixel_controllers::SetComplianceMargin&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_controllers::SetComplianceMarginRequest> should match 
// service_traits::MD5Sum< ::dynamixel_controllers::SetComplianceMargin > 
template<>
struct MD5Sum< ::dynamixel_controllers::SetComplianceMarginRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_controllers::SetComplianceMargin >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetComplianceMarginRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_controllers::SetComplianceMarginRequest> should match 
// service_traits::DataType< ::dynamixel_controllers::SetComplianceMargin > 
template<>
struct DataType< ::dynamixel_controllers::SetComplianceMarginRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_controllers::SetComplianceMargin >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetComplianceMarginRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_controllers::SetComplianceMarginResponse> should match 
// service_traits::MD5Sum< ::dynamixel_controllers::SetComplianceMargin > 
template<>
struct MD5Sum< ::dynamixel_controllers::SetComplianceMarginResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_controllers::SetComplianceMargin >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetComplianceMarginResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_controllers::SetComplianceMarginResponse> should match 
// service_traits::DataType< ::dynamixel_controllers::SetComplianceMargin > 
template<>
struct DataType< ::dynamixel_controllers::SetComplianceMarginResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_controllers::SetComplianceMargin >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetComplianceMarginResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CONTROLLERS_MESSAGE_SETCOMPLIANCEMARGIN_H
