// Generated by gencpp from file dynamixel_controllers/SetComplianceSlope.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CONTROLLERS_MESSAGE_SETCOMPLIANCESLOPE_H
#define DYNAMIXEL_CONTROLLERS_MESSAGE_SETCOMPLIANCESLOPE_H

#include <ros/service_traits.h>


#include <dynamixel_controllers/SetComplianceSlopeRequest.h>
#include <dynamixel_controllers/SetComplianceSlopeResponse.h>


namespace dynamixel_controllers
{

struct SetComplianceSlope
{

typedef SetComplianceSlopeRequest Request;
typedef SetComplianceSlopeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetComplianceSlope
} // namespace dynamixel_controllers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_controllers::SetComplianceSlope > {
  static const char* value()
  {
    return "0b655cbe1b74daf357824dcc427c1004";
  }

  static const char* value(const ::dynamixel_controllers::SetComplianceSlope&) { return value(); }
};

template<>
struct DataType< ::dynamixel_controllers::SetComplianceSlope > {
  static const char* value()
  {
    return "dynamixel_controllers/SetComplianceSlope";
  }

  static const char* value(const ::dynamixel_controllers::SetComplianceSlope&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_controllers::SetComplianceSlopeRequest> should match 
// service_traits::MD5Sum< ::dynamixel_controllers::SetComplianceSlope > 
template<>
struct MD5Sum< ::dynamixel_controllers::SetComplianceSlopeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_controllers::SetComplianceSlope >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetComplianceSlopeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_controllers::SetComplianceSlopeRequest> should match 
// service_traits::DataType< ::dynamixel_controllers::SetComplianceSlope > 
template<>
struct DataType< ::dynamixel_controllers::SetComplianceSlopeRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_controllers::SetComplianceSlope >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetComplianceSlopeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_controllers::SetComplianceSlopeResponse> should match 
// service_traits::MD5Sum< ::dynamixel_controllers::SetComplianceSlope > 
template<>
struct MD5Sum< ::dynamixel_controllers::SetComplianceSlopeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_controllers::SetComplianceSlope >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetComplianceSlopeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_controllers::SetComplianceSlopeResponse> should match 
// service_traits::DataType< ::dynamixel_controllers::SetComplianceSlope > 
template<>
struct DataType< ::dynamixel_controllers::SetComplianceSlopeResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_controllers::SetComplianceSlope >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetComplianceSlopeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CONTROLLERS_MESSAGE_SETCOMPLIANCESLOPE_H
