// Generated by gencpp from file dynamixel_controllers/SetSpeed.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CONTROLLERS_MESSAGE_SETSPEED_H
#define DYNAMIXEL_CONTROLLERS_MESSAGE_SETSPEED_H

#include <ros/service_traits.h>


#include <dynamixel_controllers/SetSpeedRequest.h>
#include <dynamixel_controllers/SetSpeedResponse.h>


namespace dynamixel_controllers
{

struct SetSpeed
{

typedef SetSpeedRequest Request;
typedef SetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeed
} // namespace dynamixel_controllers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_controllers::SetSpeed > {
  static const char* value()
  {
    return "4641bb0523a3557209606d9bd91ce33a";
  }

  static const char* value(const ::dynamixel_controllers::SetSpeed&) { return value(); }
};

template<>
struct DataType< ::dynamixel_controllers::SetSpeed > {
  static const char* value()
  {
    return "dynamixel_controllers/SetSpeed";
  }

  static const char* value(const ::dynamixel_controllers::SetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_controllers::SetSpeedRequest> should match 
// service_traits::MD5Sum< ::dynamixel_controllers::SetSpeed > 
template<>
struct MD5Sum< ::dynamixel_controllers::SetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_controllers::SetSpeed >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_controllers::SetSpeedRequest> should match 
// service_traits::DataType< ::dynamixel_controllers::SetSpeed > 
template<>
struct DataType< ::dynamixel_controllers::SetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_controllers::SetSpeed >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_controllers::SetSpeedResponse> should match 
// service_traits::MD5Sum< ::dynamixel_controllers::SetSpeed > 
template<>
struct MD5Sum< ::dynamixel_controllers::SetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_controllers::SetSpeed >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_controllers::SetSpeedResponse> should match 
// service_traits::DataType< ::dynamixel_controllers::SetSpeed > 
template<>
struct DataType< ::dynamixel_controllers::SetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_controllers::SetSpeed >::value();
  }
  static const char* value(const ::dynamixel_controllers::SetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CONTROLLERS_MESSAGE_SETSPEED_H
