// Generated by gencpp from file dynamixel_controllers/SetTorqueLimitRequest.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CONTROLLERS_MESSAGE_SETTORQUELIMITREQUEST_H
#define DYNAMIXEL_CONTROLLERS_MESSAGE_SETTORQUELIMITREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_controllers
{
template <class ContainerAllocator>
struct SetTorqueLimitRequest_
{
  typedef SetTorqueLimitRequest_<ContainerAllocator> Type;

  SetTorqueLimitRequest_()
    : torque_limit(0.0)  {
    }
  SetTorqueLimitRequest_(const ContainerAllocator& _alloc)
    : torque_limit(0.0)  {
  (void)_alloc;
    }



   typedef double _torque_limit_type;
  _torque_limit_type torque_limit;




  typedef boost::shared_ptr< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTorqueLimitRequest_

typedef ::dynamixel_controllers::SetTorqueLimitRequest_<std::allocator<void> > SetTorqueLimitRequest;

typedef boost::shared_ptr< ::dynamixel_controllers::SetTorqueLimitRequest > SetTorqueLimitRequestPtr;
typedef boost::shared_ptr< ::dynamixel_controllers::SetTorqueLimitRequest const> SetTorqueLimitRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dynamixel_controllers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ac67170532bb79d95db2a425915bbd6";
  }

  static const char* value(const ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ac67170532bb79dULL;
  static const uint64_t static_value2 = 0x95db2a425915bbd6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_controllers/SetTorqueLimitRequest";
  }

  static const char* value(const ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
float64 torque_limit\n\
";
  }

  static const char* value(const ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.torque_limit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTorqueLimitRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_controllers::SetTorqueLimitRequest_<ContainerAllocator>& v)
  {
    s << indent << "torque_limit: ";
    Printer<double>::stream(s, indent + "  ", v.torque_limit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_CONTROLLERS_MESSAGE_SETTORQUELIMITREQUEST_H
