// Generated by gencpp from file dynamixel_controllers/StartController.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CONTROLLERS_MESSAGE_STARTCONTROLLER_H
#define DYNAMIXEL_CONTROLLERS_MESSAGE_STARTCONTROLLER_H

#include <ros/service_traits.h>


#include <dynamixel_controllers/StartControllerRequest.h>
#include <dynamixel_controllers/StartControllerResponse.h>


namespace dynamixel_controllers
{

struct StartController
{

typedef StartControllerRequest Request;
typedef StartControllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartController
} // namespace dynamixel_controllers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_controllers::StartController > {
  static const char* value()
  {
    return "94c76c2df56346fcaa2611bdac54f434";
  }

  static const char* value(const ::dynamixel_controllers::StartController&) { return value(); }
};

template<>
struct DataType< ::dynamixel_controllers::StartController > {
  static const char* value()
  {
    return "dynamixel_controllers/StartController";
  }

  static const char* value(const ::dynamixel_controllers::StartController&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_controllers::StartControllerRequest> should match 
// service_traits::MD5Sum< ::dynamixel_controllers::StartController > 
template<>
struct MD5Sum< ::dynamixel_controllers::StartControllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_controllers::StartController >::value();
  }
  static const char* value(const ::dynamixel_controllers::StartControllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_controllers::StartControllerRequest> should match 
// service_traits::DataType< ::dynamixel_controllers::StartController > 
template<>
struct DataType< ::dynamixel_controllers::StartControllerRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_controllers::StartController >::value();
  }
  static const char* value(const ::dynamixel_controllers::StartControllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_controllers::StartControllerResponse> should match 
// service_traits::MD5Sum< ::dynamixel_controllers::StartController > 
template<>
struct MD5Sum< ::dynamixel_controllers::StartControllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_controllers::StartController >::value();
  }
  static const char* value(const ::dynamixel_controllers::StartControllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_controllers::StartControllerResponse> should match 
// service_traits::DataType< ::dynamixel_controllers::StartController > 
template<>
struct DataType< ::dynamixel_controllers::StartControllerResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_controllers::StartController >::value();
  }
  static const char* value(const ::dynamixel_controllers::StartControllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CONTROLLERS_MESSAGE_STARTCONTROLLER_H
