(cl:in-package pr2_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          LASTTIMESYSTEM-VAL
          LASTTIMESYSTEM
          TIMELEFT-VAL
          TIMELEFT
          AVERAGECHARGE-VAL
          AVERAGECHARGE
          MESSAGE-VAL
          MESSAGE
          LASTTIMECONTROLLER-VAL
          LASTTIMECONTROLLER
          PRESENT-VAL
          PRESENT
          CHARGING-VAL
          CHARGING
          DISCHARGING-VAL
          DISCHARGING
          RESERVED-VAL
          RESERVED
          POWERPRESENT-VAL
          POWERPRESENT
          POWERNG-VAL
          POWERNG
          INHIBITED-VAL
          INHIBITED
          BATTERY-VAL
          BATTERY
))