(cl:in-package pr2_msgs-msg)
(cl:export '(PRESENT-VAL
          PRESENT
          CHARGING-VAL
          CHARGING
          DISCHARGING-VAL
          DISCHARGING
          POWER_PRESENT-VAL
          POWER_PRESENT
          POWER_NO_GOOD-VAL
          POWER_NO_GOOD
          INHIBITED-VAL
          INHIBITED
          LAST_BATTERY_UPDATE-VAL
          LAST_BATTERY_UPDATE
          BATTERY_REGISTER-VAL
          BATTERY_REGISTER
          BATTERY_UPDATE_FLAG-VAL
          BATTERY_UPDATE_FLAG
          BATTERY_REGISTER_UPDATE-VAL
          BATTERY_REGISTER_UPDATE
))